apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: exciting-wildfowl-go 
  janus-idp.io/tekton: exciting-wildfowl-go
  backstage.io/kubernetes-id: exciting-wildfowl-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: exciting-wildfowl-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  